# Generated by Django 3.1.7 on 2021-03-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='board',
            field=models.CharField(choices=[('공지사항', '공지사항'), ('동문소식\x1c', '동문소식')], default='공지사항', max_length=12),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
