# Generated by Django 3.1.7 on 2021-03-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210310_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='board',
            field=models.CharField(choices=[('공지사항', '공지사항'), ('동문소식', '동문소식')], default='공지사항', max_length=12),
        ),
    ]
